# Based on openjdk:8, already includes lein
image: clojure:openjdk-11-lein-2.8.1
# If you need to configure a database, add a `services` section here
# See https://docs.gitlab.com/ce/ci/services/postgres.html
# Make sure you configure the connection as well

stages:
  - test_stage
  - build_stage

before_script:
  # If you need to install any external applications, like a 
  # postgres client, you may want to uncomment the line below:
  # 
  #- apt-get update -y
  #
  # Retrieve project dependencies
  # Do this on before_script since it'll be shared between both test and
  # any production sections a user adds
  # - apt-get update -y
  - lein deps

test:
  stage: test_stage
  script:
    - lein test
  only:
    - master
    - develop

build-discourje:
  stage: build_stage
  script:
    - lein with-profile discourje uberjar
  artifacts:
    paths:
      - /builds/ruben.hamers/Discourje/target/discourje.jar
    expire_in: 1 week
  only:
    - master
    - develop

build-tacas:
  stage: build_stage
  script:
    - lein with-profile tacas2020 uberjar
  artifacts:
    paths:
      - /builds/ruben.hamers/Discourje/target/tacas2020.jar
    expire_in: 1 week
  only:
    - master
    - develop